// AUTO-GENERATED by scripts/generate-registry.mjs — DO NOT EDIT.

export const pluginSubdomains = ["shopping"] as const;

export const pluginPackages: string[] = ["@devquake/plugin-shopping"];

export const reservedSubdomains = ["www","api","app","admin","auth","dashboard","mail","smtp","ftp","cdn","static","assets","status","docs","dev","staging","cpanel","webmail"] as const;
