// AUTO-GENERATED by scripts/generate-registry.mjs — DO NOT EDIT.
import type { PluginDefinition } from '@devquake/plugin-sdk';

export const pluginLoaders: Record<string, () => Promise<PluginDefinition>> = {
  'example': () => import('@devquake/plugin-example').then((m) => m.default),
};
