// AUTO-GENERATED by scripts/generate-registry.mjs — DO NOT EDIT.
import type { PluginDefinition } from '@devquake/plugin-sdk';

export const pluginLoaders: Record<string, () => Promise<PluginDefinition>> = {
  'myvault': () => import('@devquake/plugin-myvault').then((m) => m.default),
  'shopping': () => import('@devquake/plugin-shopping').then((m) => m.default),
  'utilities': () => import('@devquake/plugin-utilities').then((m) => m.default),
  'workout': () => import('@devquake/plugin-workout').then((m) => m.default),
};
