// AUTO-GENERATED by scripts/generate-registry.mjs — DO NOT EDIT.

export const pluginSubdomains = ["myvault","shopping","utilities","workout"] as const;

export const pluginPackages: string[] = ["@devquake/plugin-myvault","@devquake/plugin-shopping","@devquake/plugin-utilities","@devquake/plugin-workout"];

export const reservedSubdomains = ["www","api","app","admin","auth","dashboard","mail","smtp","ftp","cdn","static","assets","status","docs","dev","staging","cpanel","webmail"] as const;
