#!/usr/bin/env node
/**
 * Turns the Next.js standalone build into a self-contained folder that a plain
 * `npm install && node server.js` host (Hostinger managed Node.js) can run.
 *
 * Usage (after `pnpm build`):  node scripts/assemble-deploy.mjs [outDir]   (default: .deploy)
 *
 * Output:
 *   server.js            entry file (scripts/deploy-server.cjs, wraps apps/host/server.js)
 *   package.json         only runtime deps (next, react, react-dom) at the exact built versions
 *   apps/host/...        compiled app incl. .next/static and public
 */
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const hostDir = path.join(root, 'apps', 'host');
const standalone = path.join(hostDir, '.next', 'standalone');
const out = path.resolve(root, process.argv[2] ?? '.deploy');

if (!fs.existsSync(path.join(standalone, 'apps', 'host', 'server.js'))) {
  console.error('[deploy] No standalone build found. Run `pnpm build` first.');
  process.exit(1);
}

// With pnpm, Turbopack loads server-external packages through hashed aliases in
// .next/node_modules (e.g. "mysql2-<hash>"). The clean-up below deletes every node_modules
// folder, so those aliases would be missing at runtime and every page using them would 500.
// Server dependencies must be bundled instead: do not add them to `serverExternalPackages`.
const externalAliases = path.join(standalone, 'apps', 'host', '.next', 'node_modules');
if (fs.existsSync(externalAliases)) {
  console.error(
    `[deploy] Found server-external package aliases (${fs.readdirSync(externalAliases).join(', ')}).
` + '         They would be missing in the bundle. Remove them from serverExternalPackages.',
  );
  process.exit(1);
}

fs.rmSync(out, { recursive: true, force: true });
fs.cpSync(standalone, out, { recursive: true, verbatimSymlinks: true });
fs.cpSync(path.join(hostDir, '.next', 'static'), path.join(out, 'apps/host/.next/static'), {
  recursive: true,
});
if (fs.existsSync(path.join(hostDir, 'public'))) {
  fs.cpSync(path.join(hostDir, 'public'), path.join(out, 'apps/host/public'), { recursive: true });
}

// Remove traced node_modules (pnpm symlinks) and any env files; the host installs deps itself.
function clean(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.name === 'node_modules') fs.rmSync(p, { recursive: true, force: true });
    else if (e.name.startsWith('.env') && e.name !== '.env.example') fs.rmSync(p, { force: true });
    else if (e.isDirectory()) clean(p);
  }
}
clean(out);

const requireFromHost = createRequire(path.join(hostDir, 'package.json'));
const version = (pkg) => requireFromHost(`${pkg}/package.json`).version;

const pkg = {
  name: 'devquake-deploy',
  private: true,
  description: 'Prebuilt DevQuake bundle. Generated by CI - do not edit.',
  scripts: {
    build: "echo 'Already built in GitHub Actions'",
    start: 'node server.js',
  },
  engines: { node: '>=20.9.0' },
  dependencies: {
    next: version('next'),
    react: version('react'),
    'react-dom': version('react-dom'),
  },
};
fs.writeFileSync(path.join(out, 'package.json'), `${JSON.stringify(pkg, null, 2)}\n`);

// Entry file: binds the port and can load a shared settings file (DEVQUAKE_ENV_FILE).
fs.copyFileSync(path.join(root, 'scripts', 'deploy-server.cjs'), path.join(out, 'server.js'));

fs.writeFileSync(
  path.join(out, 'README.md'),
  `# DevQuake deploy bundle\n\nGenerated automatically from \`main\` by CI. Do not edit or commit to this branch by hand.\nStart: \`npm install && node server.js\` with \`ROOT_DOMAIN\`, \`PORT\` and the \`MAIN_DB_*\` variables set.\n`,
);

console.log(`[deploy] Bundle ready in ${path.relative(root, out) || out}`);
