import { brandedQrSvg } from '@devquake/ui/qr';
import { getLocale, getT } from '@/i18n/server';
import { hostUrl } from '@/lib/domain';
import { listPublicReferrals } from '@/lib/external-referrals';
import { CopyButton } from '@/components/account/copy-button';

/**
 * External referrals (ADR 0021), in the style of the Hostinger box: what it is, a button to the
 * partner and a QR code to open it on a phone. Button and QR code go through /go/<slug>, which
 * counts the visit and forwards to the partner's referral link. Managed in /admin-cp/referrals.
 */
/**
 * Caption and title on the left, the partner's logo in the top right corner. Spans the box's
 * full width, so the text and the QR code sit below it.
 */
export function ReferralHeading({
  label,
  title,
  logoUrl,
  logoAlt,
}: {
  label: string;
  title: string;
  logoUrl: string | null;
  logoAlt: string;
}) {
  return (
    <div className="flex w-full items-start justify-between gap-4">
      <div className="min-w-0">
        <p className="text-xs font-medium tracking-wider text-ink/60 uppercase dark:text-paper/60">
          {label}
        </p>
        <p className="mt-2 font-semibold">{title}</p>
      </div>
      {logoUrl ? (
        // eslint-disable-next-line @next/next/no-img-element -- small partner logo, own route
        <img
          src={logoUrl}
          alt={logoAlt}
          width={44}
          height={44}
          className="size-11 shrink-0 rounded-lg bg-white object-contain p-1 ring-1 ring-ink/10 dark:ring-paper/15"
        />
      ) : null}
    </div>
  );
}

export async function ExternalReferrals() {
  const [locale, t] = await Promise.all([getLocale(), getT('landing.referrals')]);
  const referrals = await listPublicReferrals(locale);
  if (referrals.length === 0) return null;
  return (
    <>
      {referrals.map((r) => {
        const go = `${hostUrl()}/go/${r.slug}`;
        return (
          <aside
            key={r.slug}
            className="flex flex-wrap items-start gap-x-5 gap-y-3 rounded-lg border border-ink/10 bg-white p-5 dark:border-paper/10 dark:bg-paper/5"
          >
            <ReferralHeading
              label={r.texts.label}
              title={r.texts.title}
              logoUrl={r.logoUrl}
              logoAlt={t('logoLabel', { name: r.name })}
            />
            <div className="min-w-0 flex-1 basis-56">
              <p className="text-sm text-ink/70 dark:text-paper/70">{r.texts.body}</p>
              <a
                href={`/go/${r.slug}`}
                target="_blank"
                rel="sponsored noopener"
                className="mt-4 inline-flex items-center gap-2 rounded-md bg-ink px-4 py-2 text-sm font-medium text-paper hover:bg-ink/85 focus-visible:ring-2 focus-visible:ring-quake focus-visible:outline-none dark:bg-paper dark:text-ink dark:hover:bg-paper/85"
              >
                {r.texts.button}
                <span aria-hidden="true">→</span>
              </a>
              {r.code ? (
                <div className="mt-3 flex flex-wrap items-center gap-2 text-sm">
                  <span className="text-ink/70 dark:text-paper/70">{t('code')}</span>
                  <code className="rounded bg-ink/5 px-2 py-1 font-mono font-semibold tracking-wide dark:bg-paper/10">
                    {r.code}
                  </code>
                  <CopyButton text={r.code} label={t('copyCode')} />
                </div>
              ) : null}
              <p className="mt-3 text-xs text-ink/60 dark:text-paper/60">
                {r.host ? `${r.host} · ` : ''}
                {t('disclosure')}
              </p>
            </div>
            <figure className="flex shrink-0 flex-col items-center">
              <div
                role="img"
                aria-label={t('qrLabel', { name: r.name })}
                className="size-28 overflow-hidden rounded bg-white p-1 [&>svg]:size-full"
                // Generated by @devquake/ui/qr from our own /go/<slug> address (validated slug).
                dangerouslySetInnerHTML={{ __html: brandedQrSvg(go, { margin: 1 }) }}
              />
              <figcaption className="mt-1.5 max-w-28 text-center text-xs text-ink/60 dark:text-paper/60">
                {t('scan')}
                <br />
                <a
                  href={`/go/${r.slug}/qr`}
                  download={`devquake-${r.slug}-qr.png`}
                  className="underline decoration-quake/50 underline-offset-2 hover:decoration-quake"
                >
                  {t('download')}
                </a>
              </figcaption>
            </figure>
          </aside>
        );
      })}
    </>
  );
}
