import { brandedQrSvg } from '@devquake/ui/qr';
import { hostUrl } from '@/lib/domain';

/**
 * QR code of the site's own address (landing page), for showing on a screen, slide or poster:
 * scanning it opens devquake.com. Rendered on the server as inline SVG (always sharp), with the
 * DevQuake mark in the middle; dark modules on white in both themes so every scanner can read
 * it. PNG download: /qr.
 */
export function SiteQr() {
  const url = `${hostUrl()}/`;
  const svg = brandedQrSvg(url, { margin: 1 });

  return (
    <figure className="mt-6 hidden items-center gap-4 rounded-lg border border-ink/10 bg-white p-3 sm:inline-flex dark:border-paper/10 dark:bg-paper/5">
      <div
        role="img"
        aria-label={`QR code that opens ${url.replace(/^https?:\/\//, '').replace(/\/$/, '')}`}
        className="size-24 shrink-0 overflow-hidden rounded bg-white p-1 [&>svg]:size-full"
        // Generated by @devquake/ui/qr from our own URL (no user input).
        dangerouslySetInnerHTML={{ __html: svg }}
      />
      <figcaption className="text-sm">
        <span className="font-medium">Open DevQuake on your phone</span>
        <span className="block text-ink/60 dark:text-paper/60">
          Scan the code with your camera.
        </span>
        <a
          href="/qr"
          download="devquake-qr.png"
          className="mt-1 inline-block text-xs underline decoration-quake/50 underline-offset-2 hover:decoration-quake"
        >
          Download QR code
        </a>
      </figcaption>
    </figure>
  );
}
