/**
 * The voice coach (ADR 0015): what the phone says during a workout is generated by the
 * browser's own speech synthesis (Web Speech API) from the app's texts, in the page language.
 * Settings are per device: muted, a female or male voice, and a calm, normal or motivational
 * ("gym") style.
 */

export const VOICE_GENDERS = ['female', 'male'] as const;
export const VOICE_STYLES = ['calm', 'normal', 'motivational'] as const;
export type VoiceGender = (typeof VOICE_GENDERS)[number];
export type VoiceStyle = (typeof VOICE_STYLES)[number];

export interface VoiceSettings {
  muted: boolean;
  gender: VoiceGender;
  style: VoiceStyle;
}

export const DEFAULT_VOICE: VoiceSettings = { muted: false, gender: 'female', style: 'normal' };
export const VOICE_STORAGE_KEY = 'dq-workout:voice';

export function parseVoiceSettings(raw: string | null): VoiceSettings {
  try {
    const v = raw ? (JSON.parse(raw) as Partial<VoiceSettings>) : {};
    return {
      muted: v.muted === true,
      gender: VOICE_GENDERS.includes(v.gender as VoiceGender)
        ? (v.gender as VoiceGender)
        : DEFAULT_VOICE.gender,
      style: VOICE_STYLES.includes(v.style as VoiceStyle)
        ? (v.style as VoiceStyle)
        : DEFAULT_VOICE.style,
    };
  } catch {
    return DEFAULT_VOICE;
  }
}

/** Speed and pitch of each style. */
export const STYLE_TUNING: Record<VoiceStyle, { rate: number; pitch: number }> = {
  calm: { rate: 0.9, pitch: 0.95 },
  normal: { rate: 1, pitch: 1 },
  motivational: { rate: 1.12, pitch: 1.1 },
};

// Browsers do not say whether a voice is female or male; their names usually do.
const FEMALE =
  /female|woman|zira|hazel|susan|samantha|victoria|karen|moira|tessa|fiona|serena|allison|ava|joanna|salli|kendra|kimberly|amy|emma|olivia|aria|jenny|sonia|libby|anna|hedda|katja|petra|marlene|vicki|ioana|andreea|alina|noemi|mariska|eszter|tünde|zsofia|helena|laura|paulina|google uk english female|google us english/i;
const MALE =
  /\bmale\b|\bman\b|david|mark|george|james|daniel|alex|fred|tom|oliver|ryan|guy|brian|matthew|joey|justin|conrad|stefan|markus|hans|klaus|andrei|emil|tamás|tamas|szabolcs|google uk english male/i;

export interface VoiceLike {
  name: string;
  lang: string;
  default?: boolean;
  localService?: boolean;
}

/** Guesses a voice's gender from its name; null when the name does not tell. */
export function voiceGender(name: string): VoiceGender | null {
  if (/female|woman/i.test(name)) return 'female';
  if (MALE.test(name)) return 'male';
  if (FEMALE.test(name)) return 'female';
  return null;
}

/**
 * The best voice for a language ("de-DE") and gender: same language first (exact region
 * preferred), then the wanted gender, then voices of unknown gender, then local voices.
 * null when the device has no voice for the language (the browser then uses its default).
 */
export function pickVoice<T extends VoiceLike>(
  voices: readonly T[],
  lang: string,
  gender: VoiceGender,
): T | null {
  const base = lang.slice(0, 2).toLowerCase();
  const candidates = voices.filter((v) => v.lang.replace('_', '-').toLowerCase().startsWith(base));
  if (candidates.length === 0) return null;
  const score = (v: T) => {
    const g = voiceGender(v.name);
    return (
      (v.lang.replace('_', '-').toLowerCase() === lang.toLowerCase() ? 4 : 0) +
      (g === gender ? 8 : g === null ? 2 : 0) +
      (v.localService ? 1 : 0)
    );
  };
  return [...candidates].sort((a, b) => score(b) - score(a))[0] ?? null;
}

/** Which encouragement to say or show (motivation.<style>.<key>): changes with each set. */
export function motivationKey(seed: number): string {
  return `m${(Math.abs(Math.floor(seed)) % 6) + 1}`;
}
