/**
 * The voice coach (ADR 0015): what the phone says during a workout is generated by the
 * browser's own speech synthesis (Web Speech API) from the app's texts, in the page language.
 * Settings are per device: muted, a female or male voice, and a calm, normal, motivational
 * ("gym") or crazy style (ADR 0019: a drill sergeant with the male voice, a bossy boss with the
 * female one).
 */

export const VOICE_GENDERS = ['female', 'male'] as const;
export const VOICE_STYLES = ['calm', 'normal', 'motivational', 'crazy'] as const;
export type VoiceGender = (typeof VOICE_GENDERS)[number];
export type VoiceStyle = (typeof VOICE_STYLES)[number];

export interface VoiceSettings {
  muted: boolean;
  gender: VoiceGender;
  style: VoiceStyle;
  /**
   * A voice the person picked on this device, per language ("ro" → "Microsoft Alina Online
   * (Natural) - Romanian (Romania)"). Without one the coach picks the best voice itself.
   */
  voices: Record<string, string>;
  /**
   * natural: DevQuake's neural voices (generated on the server, when configured); device: the
   * voices of this device (always used when natural voices are not available).
   */
  engine: VoiceEngine;
}

export const VOICE_ENGINES = ['natural', 'device'] as const;
export type VoiceEngine = (typeof VOICE_ENGINES)[number];

export const DEFAULT_VOICE: VoiceSettings = {
  muted: false,
  gender: 'female',
  style: 'normal',
  voices: {},
  engine: 'natural',
};
export const VOICE_STORAGE_KEY = 'dq-workout:voice';

export function parseVoiceSettings(raw: string | null): VoiceSettings {
  try {
    const v = raw ? (JSON.parse(raw) as Partial<VoiceSettings>) : {};
    return {
      muted: v.muted === true,
      gender: VOICE_GENDERS.includes(v.gender as VoiceGender)
        ? (v.gender as VoiceGender)
        : DEFAULT_VOICE.gender,
      style: VOICE_STYLES.includes(v.style as VoiceStyle)
        ? (v.style as VoiceStyle)
        : DEFAULT_VOICE.style,
      voices:
        v.voices && typeof v.voices === 'object' && !Array.isArray(v.voices)
          ? Object.fromEntries(
              Object.entries(v.voices).filter(
                ([lang, name]) => /^[a-z]{2}$/.test(lang) && typeof name === 'string',
              ),
            )
          : {},
      engine: v.engine === 'device' ? 'device' : 'natural',
    };
  } catch {
    return DEFAULT_VOICE;
  }
}

/**
 * The set of texts the coach speaks and shows (voice.<set>.*, motivation.<set>.*). "Crazy" has
 * two: army drill sergeant / brawler for the male voice, bossy boss for the female one.
 */
export type VoiceTextSet = Exclude<VoiceStyle, 'crazy'> | 'crazyMale' | 'crazyFemale';

export function voiceTextSet(settings: Pick<VoiceSettings, 'style' | 'gender'>): VoiceTextSet {
  if (settings.style !== 'crazy') return settings.style;
  return settings.gender === 'male' ? 'crazyMale' : 'crazyFemale';
}

/** Speed and pitch of each text set. */
export const STYLE_TUNING: Record<VoiceTextSet, { rate: number; pitch: number }> = {
  calm: { rate: 0.9, pitch: 0.95 },
  normal: { rate: 1, pitch: 1 },
  motivational: { rate: 1.12, pitch: 1.1 },
  // Barked orders: fast and low.
  crazyMale: { rate: 1.2, pitch: 0.8 },
  // Sharp and insistent: fast and high.
  crazyFemale: { rate: 1.15, pitch: 1.25 },
};

/**
 * Speed and pitch for an utterance. Many devices have only one voice for a language (often a
 * female one). When the voice found is not of the chosen gender (or unknown), the pitch is
 * shifted a little (lower for male, higher for female) so the choice is heard. Only a little:
 * a strong shift (the 0.55 used before 0.9.1) makes every voice sound robotic and hard to
 * understand, especially outside English.
 */
export function voiceTuning(
  settings: Pick<VoiceSettings, 'style' | 'gender'>,
  found: VoiceGender | null,
): { rate: number; pitch: number } {
  const base = STYLE_TUNING[voiceTextSet(settings)];
  if (settings.gender === 'male' && found !== 'male') {
    return { rate: base.rate, pitch: Math.max(0.7, Math.round(base.pitch * 0.82 * 100) / 100) };
  }
  if (settings.gender === 'female' && found === 'male') {
    return { rate: base.rate, pitch: Math.min(1.4, Math.round(base.pitch * 1.18 * 100) / 100) };
  }
  return base;
}

// Browsers do not say whether a voice is female or male; their names usually do.
// Whole words only: "Daniela" is not "Daniel", "Alexandra" is not "Alex".
const FEMALE =
  /\b(female|woman|zira|hazel|susan|samantha|victoria|karen|moira|tessa|fiona|serena|allison|ava|joanna|salli|kendra|kimberly|amy|emma|olivia|aria|jenny|sonia|libby|anna|hedda|katja|petra|marlene|vicki|ioana|andreea|alina|daniela|alexandra|noemi|mariska|eszter|tünde|zsofia|helena|laura|paulina|flo|sandy|shelley|grandma|monica|amelie|kathy|agnes|nicky|catherine|martha|kate|serena|google uk english female|google us english)\b/i;
const MALE =
  /\b(male|man|david|mark|george|james|daniel|alex|fred|tom|oliver|ryan|guy|brian|matthew|joey|justin|conrad|stefan|markus|hans|klaus|andrei|emil|tamás|tamas|szabolcs|aaron|arthur|rishi|martin|yannick|gordon|reed|rocko|eddy|grandpa|bruce|ralph|albert|thomas|lee|google uk english male)\b/i;
/**
 * Apple's novelty voices (sound effects, singing, whispering): never a coach, whatever their
 * name suggests, unless a language has nothing else.
 */
const NOVELTY =
  /\b(bad news|good news|bahh|bells|boing|bubbles|cellos|jester|junior|organ|superstar|trinoids|whisper|wobble|zarvox|deranged|hysterical|albert)\b/i;

export function isNoveltyVoice(name: string): boolean {
  return NOVELTY.test(name);
}

export interface VoiceLike {
  name: string;
  lang: string;
  default?: boolean;
  localService?: boolean;
}

/** Guesses a voice's gender from its name; null when the name does not tell. */
export function voiceGender(name: string): VoiceGender | null {
  if (/female|woman/i.test(name)) return 'female';
  if (MALE.test(name)) return 'male';
  if (FEMALE.test(name)) return 'female';
  return null;
}

/**
 * How natural a voice sounds, from its name: the online "Natural"/"Neural" voices (Edge,
 * Windows), Apple's "Enhanced"/"Premium" and Siri voices, then Google's voices; the old
 * compact device voices last. Higher is better.
 */
export function voiceQuality(name: string): number {
  if (/\b(natural|neural|premium|enhanced|siri)\b/i.test(name)) return 3;
  if (/\bonline\b/i.test(name)) return 2;
  if (/\bgoogle\b/i.test(name)) return 1;
  return 0;
}

/** The device's voices for a language ("ro-RO" matches "ro_RO" and "ro"), novelty voices left out. */
export function voicesFor<T extends VoiceLike>(voices: readonly T[], lang: string): T[] {
  const base = lang.slice(0, 2).toLowerCase();
  const all = voices.filter((v) => v.lang.replace('_', '-').toLowerCase().startsWith(base));
  const real = all.filter((v) => !isNoveltyVoice(v.name));
  return real.length ? real : all;
}

/**
 * The voice for a language ("de-DE") and gender: the one the person picked, if the device
 * still has it; otherwise the best: the wanted gender first, then natural-sounding voices, then
 * the exact region, then voices of unknown gender. null when the device has NO voice for the
 * language: the coach then stays silent rather than read the text with a voice of another
 * language (which sounds like nonsense).
 */
export function pickVoice<T extends VoiceLike>(
  voices: readonly T[],
  lang: string,
  gender: VoiceGender,
  preferredName?: string | null,
): T | null {
  const candidates = voicesFor(voices, lang);
  if (candidates.length === 0) return null;
  if (preferredName) {
    const chosen = candidates.find((v) => v.name === preferredName);
    if (chosen) return chosen;
  }
  const score = (v: T) => {
    const g = voiceGender(v.name);
    return (
      (g === gender ? 16 : g === null ? 4 : 0) +
      voiceQuality(v.name) * 3 +
      (v.lang.replace('_', '-').toLowerCase() === lang.toLowerCase() ? 2 : 0)
    );
  };
  return [...candidates].sort((a, b) => score(b) - score(a))[0] ?? null;
}

/** Which encouragement to say or show (motivation.<style>.<key>): changes with each set. */
export function motivationKey(seed: number): string {
  return `m${(Math.abs(Math.floor(seed)) % 6) + 1}`;
}
